version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@<your-aliyun-host>:5432/omniagent
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
